"""
make_stats_report.py
====================

Build the complete per-combination statistics tables for the README from the
saved range-expansion data, so the reported numbers are generated, not copied.
For every interaction it reports each cell shape under each sign carried in that
interaction (the same shape tested on both sides), the sector metrics, and the
full set of tests: Kruskal-Wallis across the three shapes for lineage success and
for each spatial metric, and, where the two roles carry different signs, the
Mann-Whitney comparison of each shape between the two signs.

    python scripts/make_stats_report.py
writes figures/stats_tables.md
"""

import os
import sys
import json

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

import numpy as np
from scipy import stats as sps

FIGDIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "figures"))
FAC = os.path.join(FIGDIR, "re_factorial_data.json")
MET = os.path.join(FIGDIR, "re_metrics_data.json")
OUT = os.path.join(FIGDIR, "stats_tables.md")

SHAPES = [0, 1, 2]
SHAPE_NAMES = ["cocci", "chain", "rod"]
ROW_ORDER = ["neutralism", "commensalism", "amensalism",
             "public_good", "mutualism", "competition"]
ROW_TITLE = {"neutralism": "Neutralism (0, 0)", "commensalism": "Commensalism (0, +)",
             "amensalism": "Amensalism (0, -)", "public_good": "Public good (-, +)",
             "mutualism": "Mutualism (+, +)", "competition": "Competition (-, -)"}
SIGNS = {"neutralism": (0, 0), "commensalism": (0, 1), "amensalism": (0, -1),
         "public_good": (-1, 1), "mutualism": (1, 1), "competition": (-1, -1)}
SIGN_TXT = {-1: "-", 0: "0", 1: "+"}


def _stars(p):
    if not np.isfinite(p):
        return "n/a"
    return "***" if p < 1e-3 else "**" if p < 1e-2 else "*" if p < 5e-2 else "ns"


def _ms(v):
    v = np.asarray([x for x in v if np.isfinite(x)], float)
    if v.size == 0:
        return "n/a", 0
    return f"{v.mean():.2f} ± {v.std():.2f}", v.size


def _kw(groups):
    g = [np.asarray([x for x in grp if np.isfinite(x)], float) for grp in groups]
    g = [x for x in g if x.size >= 1]
    if len(g) < 2 or all(np.ptp(x) == 0 for x in g):
        # Kruskal-Wallis needs variability; if every group is a constant, report n/a
        try:
            H, p = sps.kruskal(*g)
            return p
        except ValueError:
            return float("nan")
    try:
        H, p = sps.kruskal(*g)
        return p
    except ValueError:
        return float("nan")


def _mw(u, w):
    u = np.asarray([x for x in u if np.isfinite(x)], float)
    w = np.asarray([x for x in w if np.isfinite(x)], float)
    if u.size >= 2 and w.size >= 2:
        try:
            return sps.mannwhitneyu(u, w).pvalue
        except ValueError:
            return float("nan")
    return float("nan")


def main():
    fac = json.load(open(FAC))
    met = json.load(open(MET))
    n_fac = max(1, round(len(fac) / (6 * 9 * 2)))
    n_met = max(1, round(len(met) / (6 * 3)))

    lines = []
    lines.append("<!-- generated by scripts/make_stats_report.py, do not edit by hand -->")
    lines.append("")

    for row in ROW_ORDER:
        sgA, sgB = SIGNS[row]
        symmetric = sgA == sgB
        lines.append(f"### {ROW_TITLE[row]}")
        lines.append("")
        # success per shape under each sign
        succ_by_sign = {}
        for s in SHAPES:
            succ_by_sign[(s, sgA)] = [d["succ"] for d in fac
                                      if d["row"] == row and d["shape"] == s
                                      and d["sign"] == sgA]
            succ_by_sign[(s, sgB)] = [d["succ"] for d in fac
                                      if d["row"] == row and d["shape"] == s
                                      and d["sign"] == sgB]
        # sector metrics per shape (symmetric pairing run)
        jc = {s: [d["jc"] for d in met if d["row"] == row and d["shape"] == s] for s in SHAPES}
        xi = {s: [d["xi"] for d in met if d["row"] == row and d["shape"] == s] for s in SHAPES}
        Sc = {s: [d["S"] for d in met if d["row"] == row and d["shape"] == s] for s in SHAPES}
        Dc = {s: [d["D"] for d in met if d["row"] == row and d["shape"] == s] for s in SHAPES}

        if symmetric:
            hdr = (f"| cell shape | lineage success (sign {SIGN_TXT[sgA]}) "
                   f"| mixing jc | sector width xi | sectors S | lineages D |")
            sep = "| --- | --- | --- | --- | --- | --- |"
            lines.append(hdr)
            lines.append(sep)
            for s in SHAPES:
                a, na = _ms(succ_by_sign[(s, sgA)])
                jcm, _ = _ms(jc[s]); xim, _ = _ms(xi[s])
                scm, _ = _ms(Sc[s]); dcm, _ = _ms(Dc[s])
                lines.append(f"| {SHAPE_NAMES[s]} | {a} (n={na}) | {jcm} | {xim} "
                             f"| {scm} | {dcm} |")
        else:
            hdr = (f"| cell shape | success as role A (sign {SIGN_TXT[sgA]}) "
                   f"| success as role B (sign {SIGN_TXT[sgB]}) "
                   f"| role A vs B | mixing jc | sector width xi |")
            sep = "| --- | --- | --- | --- | --- | --- |"
            lines.append(hdr)
            lines.append(sep)
            for s in SHAPES:
                a, na = _ms(succ_by_sign[(s, sgA)])
                b, nb = _ms(succ_by_sign[(s, sgB)])
                p_role = _mw(succ_by_sign[(s, sgA)], succ_by_sign[(s, sgB)])
                jcm, _ = _ms(jc[s]); xim, _ = _ms(xi[s])
                lines.append(f"| {SHAPE_NAMES[s]} | {a} (n={na}) | {b} (n={nb}) "
                             f"| {_stars(p_role)} (p={p_role:.2g}) | {jcm} | {xim} |")

        # Kruskal-Wallis across the three shapes
        succ_pool = [succ_by_sign[(s, sgA)] + succ_by_sign[(s, sgB)] for s in SHAPES]
        p_succ = _kw(succ_pool)
        p_jc = _kw([jc[s] for s in SHAPES])
        p_xi = _kw([xi[s] for s in SHAPES])
        lines.append("")
        lines.append(f"Kruskal-Wallis across the three shapes: lineage success "
                     f"{_stars(p_succ)} (p = {p_succ:.2g}); mixing ratio "
                     f"{_stars(p_jc)} (p = {p_jc:.2g}); sector width "
                     f"{_stars(p_xi)} (p = {p_xi:.2g}). "
                     f"Replicates: success N = {n_fac} per shape pair, "
                     f"sector metrics N = {n_met} per shape.")
        lines.append("")

    open(OUT, "w").write("\n".join(lines))
    print("wrote", OUT)
    print("\n".join(lines))


if __name__ == "__main__":
    main()
